#!/bin/sh

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


pecho() { printf '%s\n' "$*"; }
error() { pecho "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
try() { "$@" || fatal "Command failed: $*"; }


if [ "$(dotfiles-config --bool --get dotfiles.manageSystem)" != "true" ]; then
  pecho 'Not updating system. See dotfiles.manageSystem config.'
  exit 0
fi


libdir=~/.local/lib/system-packages


uname_s="$(try uname -s)" || exit 1
case "$uname_s" in
  Linux)
    lsb_id="$(try lsb_release --short --id)" || exit 1
    case "$lsb_id" in
      Debian|Ubuntu)
        exec "${libdir}/update-debian"
        ;;

      *)
        fatal "Unknown Linux system: '${lsb_id}'"
        ;;
    esac
    ;;

  *)
    fatal "Unknown system: '${uname_s}'"
    ;;
esac
