#!/bin/sh

# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


export PYTHONPATH="${HOME}/.local/lib/python3/site-packages"


if ! python3 -c 'import jinja2' > /dev/null 2>&1; then
  echo 'Skipping config_merge_template because of missing dependencies.'
  exit 0
fi


exec python3 -m config_merge_template.main
