#!/bin/bash

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


for profile_dir in ~/.mozilla/firefox/*.*; do
  [[ -d "${profile_dir}" ]] || continue

  # Remove existing links to files in the all/ directory.
  for file in "${profile_dir}"/*; do
    [[ -h "${file}" ]] || continue
    link="$(readlink "${file}")" || exit 1
    [[ "${link}" = ../all/* ]] || continue
    rm "${file}" || exit 1
  done

  # Create links to files in the all/ directory.
  (
    cd "${profile_dir}/../all" || exit 1
    for link_to in *; do
      [[ -e "${link_to}" ]] || continue
      link_from="${profile_dir}/${link_to}"
      if [[ -e "${link_from}" ]] && ! [[ -h "${link_from}" ]]; then
        echo "ERROR: Not overwriting: ${link_from}" >&2
        exit 1
      fi
      ln -sf "../all/${link_to}" "${link_from}" || exit 1
    done
  ) || exit 1
done
