#!/bin/sh

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


pecho() { printf '%s\n' "$*"; }
error() { pecho "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
try() { "$@" || fatal "Command failed: $*"; }


# localedef(1) tries to read some things from the current directory, so make
# sure it only finds what we want it to find.
empty_dir="$(try mktemp -d)" || exit 1
cd "$empty_dir"


export I18NPATH=~/.local/share/i18n
try localedef -f UTF-8 -i nl_US ~/.local/share/locale/nl_US


accountsservice_user_path="$(
    try dbus-send \
      --system \
      --dest=org.freedesktop.Accounts \
      --print-reply=literal \
      /org/freedesktop/Accounts \
      org.freedesktop.Accounts.FindUserByName \
      "string:${USER}"
)" || exit 1
try dbus-send \
  --system \
  --dest=org.freedesktop.Accounts \
  --print-reply=literal \
  $accountsservice_user_path \
  org.freedesktop.Accounts.User.SetLanguage \
  string:nl_US.UTF-8
