#!/bin/bash

# Copyright 2025 David Mandelberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euxo pipefail

if [[ -z "${DISPLAY-}" ]]; then
  echo 'Not updating unimnim, because $DISPLAY is empty.'
  exit 0
fi

pip-install-system-without-deps git+https://github.com/dseomn/unimnim.git

unimnim --write-m17n ~/.m17n.d/unimnim.mim
