#!/bin/sh

# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


usage_fatal() {
  cat >&2 <<EOF
Usage: ${0} test|connect <hostname> <port>

test: Returns 0 iff this script should be used as ProxyCommand.
connect: Connects, for use in ProxyCommand.
EOF
  exit 1
}


[ "$#" = 3 ] || usage_fatal
mode="$1"
hostname="$2"
port="$3"


# Executes the arguments as a proxy.
proxy_exec() {
  case "$mode" in
    test)
      exit 0
      ;;

    connect)
      exec "$@"
      ;;

    *)
      usage_fatal
      ;;
  esac
}


# Connects to the given host ($1) and port ($2).
proxy_tcp() {
  proxy_exec nc -w 15 -q 1 "$1" "$2"
}


# For a hostname foo.example.com, check config files for foo.example.com,
# example.com, and com, in that order.
__dns_name="${hostname%.}."
while [ -n "$__dns_name" ]; do
  __config_file="${HOME}/.ssh/proxy.d/${__dns_name}sh"
  [ -f "$__config_file" ] && . "$__config_file"
  __dns_name="${__dns_name#*.}"
done


# No proxy_* function was called, so exit with a non-zero status. In test mode,
# this will prevent this script from being used as a ProxyCommand.
exit 1
