#!/bin/bash

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


pecho() { printf '%s\n' "$*"; }
fatal() { pecho "ERROR: $*" >&2; exit 1; }
try() { "$@" || fatal "'$*' failed"; }


# This bootstrap script can be run before the dotfiles get a chance to update
# the interactive shell environment. So set the path explicitly to enable
# running executables in the dotfiles.
export PATH=~/.local/bin:"$PATH"


# Unsets a local config option.
yadm_unset_local() {
  if yadm gitconfig --local --get "$1" > /dev/null; then
    try yadm gitconfig --unset "$1"
  fi
}


# Make yadm more like plain git.
try yadm_unset_local status.showUntrackedFiles


try dotfiles-update


try check-environment


# For the list of folders to check for new messages, see:
# https://searchfox.org/comm-central/rev/4514b5d76206d03ddddced18e40cdd67fde36ee7/mailnews/imap/src/nsImapIncomingServer.cpp#2713-2714
# https://searchfox.org/comm-central/rev/4514b5d76206d03ddddced18e40cdd67fde36ee7/mailnews/imap/src/nsImapMailFolder.cpp#2365-2366
cat <<EOF


Automatic bootstrapping done. Next steps:

Firefox:
  * Add profiles.
  * Re-run dotfiles-update.
  * Configure profiles.

Thunderbird:
  * Add profiles.
  * Re-run dotfiles-update.
  * Install CardBook.
  * Add email accounts.
  * Add calendar accounts.
  * Add contacts accounts.
  * Set these folders to explicitly check for new messages:
    * Junk
    * Sent
    * Trash

Pidgin:
  * Configure Pidgin.
  * Add accounts.
EOF
