# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- dir: org
  children:
  - dir: mate
    children:
    - dir: settings-daemon
      reset: true
      children:
      - dir: plugins
        children:
        - dir: media-keys
          children:
            # TODO(https://github.com/mate-desktop/mate-settings-daemon/issues/256):
            # Change these to arrays of both the custom shortcuts and the
            # default shortcuts.
          - key: previous
            value: "'<Alt>comma'"
          - key: next
            value: "'<Alt>period'"
          - key: play
            value: "'<Alt>slash'"
          - key: volume-down
            value: "'<Control>comma'"
          - key: volume-up
            value: "'<Control>period'"
          - key: volume-mute
            value: "'<Control>slash'"
