#!/bin/bash

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -euxo pipefail


cleanup_actions=()
trap 'exit 1' HUP INT TERM
trap 'for cleanup in "${cleanup_actions[@]}"; do eval "$cleanup"; done' EXIT


to_install="$(dotfiles-config --get-all system-packages.debian.install)"
to_install_ret=$?
if [[ "$to_install_ret" != 0 ]] || [[ -z "$to_install" ]]; then
  printf '%s\n' 'Configure system-packages.debian.install first.'
  exit 1
fi


# Install this script's dependencies.
sudo apt-get ${DOTFILES_BOOTSTRAP_APT_GET_OPTIONS-} install devscripts


workdir="$(mktemp -d)"
cleanup_actions+=('rm -rf "${workdir}"')


cp -LR ~/.config/system-packages/debian "${workdir}"


version="$(date --utc +%Y%m%d.%H%M%S)"


for package_dir in "${workdir}/debian"/*; do
  [[ -d "${package_dir}" ]] || continue
  (
    cd "${package_dir}"
    debchange \
      --create \
      --distribution=UNRELEASED \
      --empty \
      --newversion="$version" \
      --package="${package_dir##*/}" \
      'Placeholder changelog entry.'
    debuild --no-sign
  )
done


(
  cd "${workdir}/debian"
  dpkg-scanpackages . > Packages
)


sudo apt-get ${DOTFILES_BOOTSTRAP_APT_GET_OPTIONS-} \
  --with-source "${workdir}/debian/Packages" install $to_install
