[general]
# Some games have audio positioning bugs due to only/primarily being tested on
# stereo systems. Ideally those should be fixed, but in the meantime,
# uncommenting this works around those bugs.
#channels = stereo
