# Copyright 2025 David Mandelberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -s @window-type '#{?'
set -sa @window-type '#{==:#{window_name},local},local,'
set -sa @window-type '#{m/r:^podman($| ),#{window_name}},container,'
set -sa @window-type '#{m/r:^ssh($| ),#{window_name}},remote,'
set -sa @window-type 'invalid}'

set -s @window-type-emoji '#{?'
set -sa @window-type-emoji '#{==:#{E:@window-type},container},🦭,'
set -sa @window-type-emoji '#{==:#{E:@window-type},local},🏡,'
set -sa @window-type-emoji '#{==:#{E:@window-type},remote},🛂,'
set -sa @window-type-emoji '❓}'

# Keep in sync with ~/.config/shell/interactive.d/50-prompt-50-core.bash
set -s @window-type-style '#{?'
set -sa @window-type-style '#{==:#{E:@window-type},container},fg=magenta reverse,'
set -sa @window-type-style '#{==:#{E:@window-type},local},fg=green reverse,'
set -sa @window-type-style '#{==:#{E:@window-type},remote},fg=yellow reverse,'
set -sa @window-type-style 'fg=red reverse}'
